---
- hosts: app
  become: true
  tasks:
    - name: install app components
      apt: name={{item}} state=present update_cache=yes

      with_items:
        - libpq-dev
        - python-dev
        - python-psycopg2
        - python-pip
        - python-virtualenv
        - supervisor

    - name: copy demo app source
      copy: src=wcdemo/perfdemo/ dest=/var/www/perfdemo mode=0755

    - name: setup python virtualenv
      pip: requirements=/var/www/perfdemo/requirements.txt virtualenv=/var/www/perfdemo/venv

    - name: django migrate
      django_manage:
        command: makemigrations
        app_path: /var/www/perfdemo/
        pythonpath: /var/www/perfdemo/

    - name: django migrate
      django_manage:
        command: migrate
        app_path: /var/www/perfdemo/
        pythonpath: /var/www/perfdemo

    - name: django migrate
      django_manage:
        command: initdb
        app_path: /var/www/perfdemo/
        pythonpath: /var/www/perfdemo

    - name: copy supervisor conf
      copy: src=supervisor.conf dest=/etc/supervisor/conf.d mode=0755
      notify:
        - reread supervisord
        - update supervisord
        - restart supervisord

  handlers:
    - name: restart supervisord
      sudo: yes
      service: name=supervisor state=restarted
     
    - name: reread supervisord
      sudo: yes
      command: supervisorctl reread
      
    - name: update supervisord
      sudo: yes
      command: supervisorctl update
      #      notify: restart apache2
      #
      #    - name: setup python virtualenv
      #      pip: requirements=/var/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
      #      notify: restart apache2
      #
      #    - name: deactivate default apache sites
      #      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      #      notify: restart apache2
      #
      #    - name: activate demo apache site
      #      file: src=/etc/apache2/sites-available/demo.conf dest=/etc/apache2/sites-enabled/demo.conf state=link
      #      notify: restart apache2
      #
      #    handlers:
      #      - name: restart apache2
      #        service: name=apache2 state=restarted
      #
      #```
