---
- hosts: database
  become: yes
  gather_facts: true
  vars:
    dbname: wcdemo 
    dbuser: wcdemo
    dbpassword: wcdemo
    datadog_api_key: "061e1093f0ae55ede1304666cdda1e84"
    datadog_checks:
      postgres:
        init_config:
        instances:
          - host: localhost
            port: 5432
            username: datadog
            password: abc123
            tags:
              - test
              - env:ans-demo
  roles:
    - postgres
    - Datadog.datadog
