---
- hosts: app
  become: true
  vars:
    dbname: wcdemo 
    dbuser: wcdemo
    dbpassword: wcdemo
    datadog_api_key: "061e1093f0ae55ede1304666cdda1e84"
    datadog_checks:
      gunicorn:
        init_config:
        instances:
          - proc_name: perfdemo
  roles:
    - Datadog.datadog
    - django
